### ISSUE TITLE
Create basic client-server implementation using gRPC

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/key-mgmt#100]
Complete the following tasks to get spun up:
- [ ] Follow the tutorial for [tonic library](https://docs.rs/tonic/latest/tonic/) - https://github.com/hyperium/tonic/blob/master/examples/routeguide-tutorial.md
- [ ] Learn the [gRPC Interface Definition Language (IDL)](https://developers.google.com/protocol-buffers/docs/proto3) syntax to create protocol buffers 
- [ ] Create a basic client-server via a ping/pong type protocol buffer

**Comment by picklenerd** [comment]
Implemented in https://github.com/boltlabs-inc/dams-tonic-toy
