### ISSUE TITLE
Select and integrate AEAD library

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#107]
The cryptography module depends on an authenticated encryption with associated data (AEAD) scheme.

Also, think about context for each encryption scheme and validation of the type (e.g. at deserialization or generation).

- [x] choose a library that implements an AEAD scheme (or chose to implement it ourselves)
- [x] Update encryption-related types to be wrappers around the expected chacha types (key, associated data, encrypted)
- [x] Implement generic encryption + decryption
- [x] implement encryption + decryption of the storage key under the master key
- [x] implement encryption + decryption of a secret under the storage key
- [x] updated all the tagged documentation in the crypto module to reference the selected scheme
- [x] note choice via boltlabs-inc/key-mgmt-spec#70

**Comment by marsella** [comment]
[RFC 5116](https://www.rfc-editor.org/rfc/rfc5116.html) has recommended AEAD schemes based on AES, and links to papers with the full algorithms and security proofs.

**Comment by indomitableSwan** [comment]
Can you link to the relevant issue in key-mgmt-spec? @marsella

**Comment by indomitableSwan** [comment]
In line with our other dependency decisions, it would be reasonable to choose [Rust Crypto's chacha20poly1305 implementation](https://github.com/RustCrypto/AEADs/tree/master/chacha20poly1305).

This repository has at least undergone one audit by NCC.

The other option I might consider is a nonce misuse-resistant scheme like AES-GCM-SIV ([RFC 8452](https://www.rfc-editor.org/rfc/rfc8452.html)), but RustCrypto's implementation of this has not been audited and there are performance drawbacks to choosing this option.
