### ISSUE TITLE
Add develop branch to CI

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#112]
When we switched development to be working primarily off the `develop` branch instead of main, we added branch protection in the settings but didn't update the CI to run on pull requests to `develop`. We need to add that back in!

In fact, I think this is a good opportunity to revisit when our pipelines run. We currently have
`rust.yml` does all the built-in Rust checks. This should keep running on every pull request to develop. It also runs on `push` right now, which seems unnecessary to me while we have branch protection.

`e2e-test.yml` This runs the full test suite. I am not sure it does anything different from Rust right now because we don't have a separate integration test suite like we did in zeekoe (the integration tests don't use a separate harness in key-mgmt; they're treated as a single, normal integration test). 

End-to-end tests were separated from `rust` because we were worried about integration tests taking too long, so they run on a schedule (but also on pull requests, because they didn't actually take too long?) Maybe we can just run them with the normal tests?

`audit.yml` This runs a daily audit to make sure none of our dependencies went out of date. I think this is fine to keep, but we should confirm which branch it's running on (I think both `main` and `develop`, so we can figure out whether issues are urgent bug fixes in the released product vs in development).

- [x] Update rust (and end to end?) tests to run on the develop branch
- [x] Decide if we want a policy change on running end-to-end tests and implement it if so

**Comment by picklenerd** [comment]
I like having the Rust checks run on `push` just as a sanity check. Looks like the e2e tests would double the amount of time CI takes so keeping that on `pull_request` makes sense. I would agree with not running them on a schedule since they don't seem to be pulling in any unversioned dependencies.

**Comment by picklenerd** [comment]
I realized the `push` checks would have to be enabled for every branch to get the situation I described. Seems easy enough to get CI to re-run with just the `pull_request` trigger so I just removed the `push` trigger in my PR.
