### ISSUE TITLE
Write tonic helper functions for registration

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#123]
The registration protocol has some additional functionality that needs to be added, describe [in the spec](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/cryptographic_flows.md#register). This involves additional messages passed between the client and server.

Per comments in #98, sending messages requires defining some helper functions to enforce the protocol message ordering. The additional messages include:
1. The client sends a registration request (type not defined at time of writing), including a user id and encrypted storage key.
2. Maybe the server sends a success indicator? Or they just close the channel.

This can be closed when
- [x] Define the registration request type
- [x] Define any tonic infrastructure / helper functions needed to execute the protocol 

NB: @vidyaap or @picklenerd can review this issue text and edit for clarity if it doesn't accurately reflect how tonic works.

**Comment by picklenerd** [comment]
This think this is enough detail for a ticket.

We can break down the helper functions if we want. You can see the existing ones here:
https://github.com/boltlabs-inc/key-mgmt/blob/tonic-registration/dams-key-server/src/command/register.rs#L89

Basically, we have one to ensure that the message is the right type and one to process the message and generate a response. I don't think we need to put these details in the tickets though.
