### ISSUE TITLE
Message processing system design and prototype

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#128]
## Initial Design Ideas

This server-side part of this system should roughly follow the steps below. For the purposes of this example, we assume that the client sends the first message and that messages alternate one at a time between the client and server.

1. Receive a request from `tonic`
    - This request will contain a channel that the server can use to send messages to the client
1. Send a response from `tonic` containing a channel that the client can use to send messages to the server
1. Receive a generic encrypted message from the client on the channel
1. Decrypt the message
1. Deserialize the message into the type expected by the first step of the protocol
    - If the message can not be deserialized into this type, return an error
1. Process the message according to the first step of the protocol and return a message to be sent back to the client 
1. Serialize the message into the generic message format
1. Encrypt the message
1. Send the message to the client over the channel
1. Repeat until protocol is complete

The generic message format would be defined in the protobuf definitions and look something like this:

```
message EncryptedMessage {
  // Encrypted bytes
  bytes content = 1;
}
```

Message types for individual steps in the protocol would be defined by normal Rust types. These will be easier to work with than generated protobuf types and give us more flexibility in leveraging Rust's type system to implement protocols.

For running the steps of the protocol in the middle of this message handling process, I think the simplest solution would be to provide a list of functions where each function represents one step in the process. I think it would be nice if the protocol was laid out in a simple linear format that looks like a list of steps. Something like this:

```rust
protocol! {
    context;

    first_step,
    second_step,
    third_step,
}
```

Each item in the list would be a function with a signature:

```rust
async fn first_step(context: &Context, message: FirstStepInputMessage) -> Result<FirstStepOutputMessage, Error>;
```

In this example `Context` would contain things like the database handle and shared RNGs.

The `protocol!` macro would expand to something like:

```rust
    // first_step
    let encrypted_message = read_from_channel(rx).await?;
    let decrypted_message = decrypt(encrypted_message);
    let message: FirstStepInputMessage = deserialize(decrypted_message);
    let response = first_step(&context, message).await?;
    send_to_channel(tx, response).await?;

    // repeat for each step
```

These are just my ideas to get started. Certain steps of this design may present challenges that are difficult to see until the compiler gets mad.

**Difficulty**: Medium
**Confidence**: Low
**Estimate**: 3-5 days

**Comment by picklenerd** [comment]
We could also wrap protocol process in some kind of `Session` object that hold the state of the process and can be fed messages. Everything after the encrypted message is received could be handled within this object. If we create this object in a serializable way, this could make it a lot easier to resume sessions that get disconnected.

I'm not sure how much this would overlap with the old `Session` type and if it would have the same problems.

**Comment by jakinyele** [comment]
@indomitableSwan is working on an alternative approach based on authenticating each message sent over the channel. This would mean something like this:

1. Receive a request from `tonic`
    * This request will contain a channel that the server can use to send messages to the client
2. Send a response from `tonic` containing a channel that the client can use to send messages to the server
3. Receive a message from the client on the channel
4. Extract the MAC from the message
5. Retrieve the `session-key` from context and verify the MAC with the message
    * If the message fails the MAC check, then return a message auth error
6. Deserialize the message into the type expected by the first step of the protocol
7. Send the message to the client over the channel
8. Repeat until the protocol is complete

Note that this alternative approach doesn't preclude your design ideas here:

> Message types for individual steps in the protocol would be defined by normal Rust types. These will be easier to work  with than generated protobuf types and give us more flexibility in leveraging Rust's type system to implement protocols.
> 
> For running the steps of the protocol in the middle of this message handling process, I think the simplest solution would be to provide a list of functions where each function represents one step in the process. I think it would be nice if the protocol was laid out in a simple linear format that looks like a list of steps.
> ...

However, I'm curious what your approach would be if we didn't necessarily require an extra encryption layer over the channel?

**Comment by picklenerd** [comment]
In general, I don't think anyone should have to work with generated protobuf types outside of the transport layer. They shouldn't be exposed outside of the library unless library consumers are implementing the transport layer themselves. The generated types are not fun to work with for a variety of reasons.

We could define the message types in protobuf and have duplicate types that we convert to for consumption. I did this is my last project that used protobuf. I'm not a fan of this approach but it's better than working with the types directly.

We could also continue to send generic messages as bytes and deserialize them directly to Rust types. This would remove the need for a lot of duplicate definitions and boilerplate, but we'd need to look into encoding schemes (MessagePack and Flexbuffers looked promising when I researched this) and we might end up with something slower than using protobuf types and converting to Rust types. It might be worth benchmarking.

I'd prefer the second option just to minimize the amount of code keep the protobuf definitions lean but I might be overlooking things.

The third option would be to use the protobuf definitions directly. If our messages are all comprised of primitive types and all we'll ever do is pull data out of them, this might be a good option. If they're going to have C-style enums, nested structs, or `oneof` definitions then I don't think we should go with this option.

**Comment by picklenerd** [comment]
I built a small demo project here that covers a few approaches I discussed above. The [README](https://github.com/boltlabs-inc/message-handling-demos/blob/main/README.md) explains how it all works and the advantages and disadvantages of each approach.

https://github.com/boltlabs-inc/message-handling-demos

**Comment by picklenerd** [comment]
Based on the demo, my recommendation would depend on where we land with the extra layer of encryption.

If we think there's a good chance we'll have the extra layer of encryption then the generic messages make the most sense. With the extra encryption layer, we're going to have to send raw bytes over the channel no matter what so this gives what we need without a bunch of unnecessary types defined in protobuf.

If the extra encryption layer is unlikely, defining message types in protobuf and converting them to Rust types produces the cleanest code with the only cost being some boilerplatey conversion functions. The content of the conversion functions has to be written in both of the protobuf examples in order to validate the messages, so the only real overhead here is the Rust syntax to implement traits.

**Comment by picklenerd** [comment]
Based on the demo, my recommendation would depend on where we land with the extra layer of encryption.

If we think there's a good chance we'll have the extra layer of encryption then the generic messages make the most sense. With the extra encryption layer, we're going to have to send raw bytes over the channel no matter what so this gives what we need without a bunch of unnecessary types defined in protobuf.

If the extra encryption layer is unlikely, defining message types in protobuf and converting them to Rust types produces the cleanest code with the only cost being some boilerplatey conversion functions. The content of the conversion functions has to be written in both of the protobuf examples in order to validate the messages, so the only real overhead here is the Rust syntax to implement traits.

**Comment by indomitableSwan** [comment]
> Based on the demo, my recommendation would depend on where we land with the extra layer of encryption.
> 
> If we think there's a good chance we'll have the extra layer of encryption then the generic messages make the most sense. With the extra encryption layer, we're going to have to send raw bytes over the channel no matter what so this gives what we need without a bunch of unnecessary types defined in protobuf.
> 
> If the extra encryption layer is unlikely, defining message types in protobuf and converting them to Rust types produces the cleanest code with the only cost being some boilerplatey conversion functions. The content of the conversion functions has to be written in both of the protobuf examples in order to validate the messages, so the only real overhead here is the Rust syntax to implement traits.

Until we have a stand-alone secure channel implementation that offers mutual authentication of the asset owner and key server as well as confidentiality and integrity, we will have some sort of "extra message processing", whether it's encryption/decryption or adding/verifying authentication tags. I have a PR that describes, at a high level, the switch from encryption to tags in https://github.com/boltlabs-inc/key-mgmt-spec/pull/86, which might make this point clearer.

**Comment by picklenerd** [comment]
We discussed this in our DAMS development meeting this morning and decided to go with the generic messages for now because they're more flexible and would allow us to proceed without being blocked on decisions about the extra encryption layer.

I have created an implementation issue (#152) for developing this system. The design and prototype are complete so I am closing this issue.
