### ISSUE TITLE
Create a list of technical definitions

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#129]
It would be helpful to list out some of the definitions for things like `protocol` and `session`. They could probably have their own section in the glossary of the spec.

**Comment by picklenerd** [comment]
Wrong project!

https://app.zenhub.com/workspaces/bolt-team-60886be9e01f13000e361d92/issues/boltlabs-inc/key-mgmt-spec/66

**Comment by marsella** [comment]
FYI, there is an option on Github to transfer an issue between repositories! You are not the first one to do this :)
