### ISSUE TITLE
Implement public cryptography for registration

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#131]
The crypto module provides some "wrapper" functions that bundle together multiple cryptographic operations correctly for use in protocols. For registration, this includes the `create_and_encrypt_storage_key` function. This is steps 1iii, 1iv, and 1v in [the registration protocol](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/cryptographic_flows.md#register). Close this issue when it's implemented.

The registration step also requires `UserId` generation by the key server; see the [spec](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/systems-architecture.md#opening-a-registration-session) . 

The session holds the session key as plain bytes. Replace this with a proper named type like `SessionKey(u8; 64)`.

**Comment by indomitableSwan** [comment]
@marsella Shouldn't this ticket be implemented by a cryptographer?
