### ISSUE TITLE
Implement the generate-and-store flow

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#136]
The [generate-and-store flow](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/cryptographic_flows.md#generate-and-store-a-secret) is a multi-message protocol between client and server.
Per comments in #98, sending messages requires defining some helper functions to enforce the protocol message ordering. In generation, these are:

1. The client sends a storage request (type not defined at time of writing), including a user id.
2. The key server sends a `KeyId`
3. The client sends an encrypted `Secret`
4. The key server sends a success message

- [x] Define client and server message types and serialization into / from tonic messages
- [x] Implement client-side protocol - sends request, and encrypted secret for storage; receives new key ID
- [x] Implement server-side protocol - receives request and stores encrypted secret; sends key ID
- [ ] Integration tests

**Comment by indomitableSwan** [comment]
There are some fixes [about to be merged](https://github.com/boltlabs-inc/key-mgmt-spec/pull/119) in the spec that pertain to this PR. Additionally, for clarification, this ticket references "Local secret generation with remote encrypted backup" as opposed to "remote-only secret generation and storage".
