### ISSUE TITLE
Write tonic helper functions for retrieve flow

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#137]
The [retrieve flow](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/cryptographic_flows.md#retrieve-a-secret) is a multi-message protocol between client and server.
Per comments in #98, sending messages requires defining some helper functions to enforce the protocol message ordering. In retrieval, these are:

1. The client sends a retrieval request, including a user id and key id
2. The key server sends an encrypted secret

- [ ] Define the retrieval request type
- [ ] Define any tonic infrastructure / helper functions needed to execute the protocol

**Comment by picklenerd** [comment]
Partially made obsolete by #152, the rest can be covered in #73.
