### ISSUE TITLE
Refactor message handling to use generic messages

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#152]
The existing pattern for processing messages is cumbersome and error-prone. We went through a design and prototyping phase in #128. We have decided to use a generic message type in the protobuf definitions and define our message types directly in Rust.

This issue is complete when:

- [ ] The generic message system from [the demo project](https://github.com/boltlabs-inc/message-handling-demos) is implemented.
- [ ] Existing endpoints for registration and authentication are refactored to use this syste,

**Comment by indomitableSwan** [comment]
This seems like a pretty large issue: should it perhaps be split into two?

**Comment by picklenerd** [comment]
I'd prefer to keep it as a single issue since it'll be a single PR. The system itself is handled by a relatively small macro so the bulk of the work here is refactoring.
