### ISSUE TITLE
Handle message authentication

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#186]
Messages sent between the client and server should have a MAC authentication attached to them once registration and authentication are complete. Per discussion with @picklenerd, this is essentially a transport-layer problem and can be accomplished by updating the protobuf and conversion layers without changing the places where messages are actually sent and received.

- Add a new (optional) `mac` field to the `Message` protobuf.
- Update the transformation between types and messages. Right now, the `impl_message_conversion` macro does the same thing for all messages, just serializing and deserializing the Message content. To support authentication, we want an additional conversion that serializes and creates a MAC tag / checks the MAC tag and deserializes. For each message sent in each subprotocol, we'll implement exactly one of these conversions, depending on whether the message is authenticated or not.
- Update `Channel` type to either hold an (optional?) session key or update the `send` and `receive` functions to take a session key as a parameter.
- This requires additional cryptography support - a `Tag<T>` type that holds the MAC for a `T`, a named `SessionKey` (instead of the `[u8; 64]` currently used), and a sign/verify implementation.

This epic implements the changes described in boltlabs-inc/key-mgmt-spec#86.

**Comment by indomitableSwan** [comment]
This epic description is out of date. Closing because we should create a fresh plan for session management.
