### ISSUE TITLE
Check cryptography library for completeness

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#19]
Add missing, required public APIs for the DAMS application-level cryptography library.
Create placeholders and add description and requirements to the specification.
Dependencies: Select and add requirements to the specification.

This should also include validation of the `DigitalAssetKey` type - [see discussion raised here](https://github.com/boltlabs-inc/key-mgmt/pull/21#discussion_r894413577)

**Comment by marsella** [comment]
I think this will be pushed off, since Phase 0 Part 1 is focused primarily on external APIs and doesn't reveal any of the underlying, general cryptography modules.

I would vote to update the description and release number to "Design the cryptography library from scratch, including misuse-resistant representations of all underlying cryptographic elements" and DAM Phase 1.

It's not quite clear to me which cryptography library this issue is referencing - the "underlying" generalized cryptography or the DAMS specific components. My updated description assumes the former.

**Comment by marsella** [comment]
My previous comment is incorrect. This issue relates to the DAMS specific cryptographic components - primarily digital asset management use permissions and restrictions and transaction signatures.

**Comment by indomitableSwan** [comment]
Closed as a result of revised development plan.
