### ISSUE TITLE
Improve database uniqueness enforcement

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#197]
As of #186, the key server database holds a `UserId` and an `AccountName` for each user. These fields must both be unique. During the register flow, the server manually checks this with the `find_user` and `find_user_by_id` methods. If both of these pass, then they add the user to the database.

However, this opens up a possible race condition where a user with the same id / name gets added between the time of the uniqueness check and the database update. We can prevent this by using a MongoDB index that enforces uniqueness of those fields.

@marsella tried to implement this during the course of #178 but ran into a problem where the tests had inconsistent failing behavior because of the uniqueness requirement, even after dropping the entire DB at the start of each test. This sometimes happened in the new unit tests for the database and sometimes in the integration tests. After rebasing, it sometimes didn't happen at all.

@jwantz pointed out
> If we are generating the `UserId` under the hood, then why not let the DB do it for us as part of the insert? (My understanding is that the `user_id` would be the primary key for the table.) Then we really only need to worry about the `account_name`.

- [ ] Decide whether to use an index / at-time-of-insert uniqueness guarantee
- [ ] Fix the tests

**Comment by indomitableSwan** [comment]
@marsella Does it matter that for all practical purposes, there will never be a `user_id` collision? Whereas we expect collisions for `account_name`?

**Comment by marsella** [comment]
It's worth being aware of. If we switch to mongo-generated user IDs instead of doing our own (per @jwantz 's suggestion), I think they're guaranteed to be unique already. But in either case, we should have insertion-time enforcement of the uniqueness of account names, so this still needs to be addressed.
