### ISSUE TITLE
Update module / crate structure

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#23]
Separate the existing modules into crates:

1. dams-crypto (lib)
2. dams-local-client (lib)
3. dams-remote-client (lib)
4. dams-key-server (bin)
5. dams (lib)

`dams` will have all the shared utility stuff that is used in multiple crates.

(Check crate name standards first - should the -s be _s?)

**Comment by indomitableSwan** [comment]
Closed by PR #57.
