### ISSUE TITLE
Improve logging interface

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#232]
The current logging interface works well in the middle of a protocol but it's not currently possible to log operations before the first message is passed.

In order to get create a log entry at the beginning of a protocol, we need either the user id or the account name. If we add the account name to the base message type, we would be able to create a log entry before processing the first message. The updated message type would look something like this:

```proto
message Message {
  bytes content = 1;
  string account_name = 2;
}
```

With this change to the message type, we can add the account name and operation type to the server's `Context` type. This will allow us to update the `log` function to take a `Context` as a parameter instead of specifying a bunch of redundant parameters.

**Comment by marsella** [comment]
If we do this, we should also add validation once we process the content to make sure the claimed account name matches the account that's actually getting operated on.

**Comment by vidyaap** [comment]
Note from dev sync - we should look at how to add headers to the tonic RPC messages so that we can pull that metadata instead of relying on the messages in the stream to get the user_id from.
