### ISSUE TITLE
Implement ECDSA signing

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#235]
Choose an ECDSA library and integrate it into the outline defined in #234.

- [x] Choose ECDSA library
- [x] Update key, message, and signature types to be wrappers around the library-defined types (and update conversions+tests appropriately)
- [x] Update generic signing and verification methods to call the library
- [x] Add correctness tests (sign + verify works, verifying the wrong message doesn't work, signing twice produces different signatures, flipping bits in the signature doesn't work)
- [x] Make sure signing key pair domain separator still matches dependency.
- [x] Update other generation functions (remote, import) to use library.
- [x] Update `Export` conversion functions to put the associated data and key material in the correct places (and add tests)

**Comment by marsella** [comment]
I reviewed available ECDSA-over-secp256k1 libraries. 
It seems to me like the Rust Crypto version is the best option, with the big caveat that it might not work as well in the SGX environment. But it would be compatible with all the other crypto libraries we use, I trust the cryptographers building it, and I think it has the nicest API. 

Would be nice to get @indomitableSwan and @picklenerd to weigh in on this before I fully commit. See more detailed notes below:

[secp256k1](https://docs.rs/secp256k1/latest/secp256k1/)
- This is a wrapper around a C? library by Peter Wuille, a bitcoin core developer. Hosted by the rust bitcoin community.
- No security claims re: audits or constant-time behavior.
- abstractions seem fine. Generating messages isn't super misuse-resistant. We can use their custom hasher or hash things ourselves -- I don't love the idea of having multiple implementations of the same hash function.
- It seems to have a no-std option, which might be helpful when we get into SGX.
- No shared API with, say, an EdDSA implementation.
- 177 crates use it

[RustCrypto k256](https://docs.rs/k256/latest/k256/)
- Pure Rust secp256k1 elliptic curve library with ECDSA sign/verify
- Not independently audited. Probably, but not definitely constant time.
- lower-level but more misuse-resistant API (message are just bytes, hashing seems hidden). Uses the same hash library as us.
- not sure about std
- implements the signature trait that is shared with eddsa over curve 25519 (is that the curve we want?)
- 72 crates use it

[libsecp256k1](https://docs.rs/libsecp256k1/latest/libsecp256k1/)
- Pure rust elliptic curve library (for "fast ECDSA signatures", but not clear if they have any particular optimizations) by parity tech, blockchain infra company
- No notes on audits. Some functions have inline comments about being constant-time, but many are explicitly _not_.
- relevant functions are just on the library. Seems like you have to hash your own message, but it doesn't document this.
- Explicit no-std option
- Parity Tech doesn't have an eddsa implementation (just an outated fork of the dalek-cryptography library)
- tests against the bitcoin crate
- 88 crates use it

signatory by iqlusion inc
- Not under active development for at least a year, some weird stuff about explicitly not zeroizing certain types

**Comment by indomitableSwan** [comment]
> I reviewed available ECDSA-over-secp256k1 libraries. It seems to me like the Rust Crypto version is the best option, with the big caveat that it might not work as well in the SGX environment. But it would be compatible with all the other crypto libraries we use, I trust the cryptographers building it, and I think it has the nicest API.
> 
I think we can't assume that we will make the correct dependency choice at this stage, so I would be OK with using RustCrypto's ECDSA implementation on secp256k1 for now. The main unknown is enclave integration, as you point out.

> Would be nice to get @indomitableSwan and @picklenerd to weigh in on this before I fully commit. See more detailed notes below:
> 
> [secp256k1](https://docs.rs/secp256k1/latest/secp256k1/)
> 
> * This is a wrapper around a C? library by Peter Wuille, a bitcoin core developer. Hosted by the rust bitcoin community.
> * No security claims re: audits or constant-time behavior.
> * abstractions seem fine. Generating messages isn't super misuse-resistant. We can use their custom hasher or hash things ourselves -- I don't love the idea of having multiple implementations of the same hash function.
> * It seems to have a no-std option, which might be helpful when we get into SGX.
> * No shared API with, say, an EdDSA implementation.
> * 177 crates use it
> 
> [RustCrypto k256](https://docs.rs/k256/latest/k256/)
> 
> * Pure Rust secp256k1 elliptic curve library with ECDSA sign/verify
> * Not independently audited. Probably, but not definitely constant time.
> * lower-level but more misuse-resistant API (message are just bytes, hashing seems hidden). Uses the same hash library as us.
> * not sure about std
> * implements the signature trait that is shared with eddsa over curve 25519 (is that the curve we want?)

Do you mean Edwards25519 for curve? That is, is it the Ed25519 signature scheme that is implemented here (so EdDSA on the Edwards25519 curve)? I hate the way they named these; I always get confused.

> * 72 crates use it
> 
> [libsecp256k1](https://docs.rs/libsecp256k1/latest/libsecp256k1/)
> 
> * Pure rust elliptic curve library (for "fast ECDSA signatures", but not clear if they have any particular optimizations) by parity tech, blockchain infra company
> * No notes on audits. Some functions have inline comments about being constant-time, but many are explicitly _not_.
> * relevant functions are just on the library. Seems like you have to hash your own message, but it doesn't document this.
> * Explicit no-std option
> * Parity Tech doesn't have an eddsa implementation (just an outated fork of the dalek-cryptography library)
> * tests against the bitcoin crate
> * 88 crates use it
> 
> signatory by iqlusion inc
> 
> * Not under active development for at least a year, some weird stuff about explicitly not zeroizing certain types

**Comment by marsella** [comment]
>  > - implements the signature trait that is shared with eddsa over curve 25519 (is that the curve we want?)
>
> Do you mean Edwards25519 for curve? That is, is it the Ed25519 signature scheme that is implemented here (so EdDSA on the Edwards25519 curve)? I hate the way they named these; I always get confused.

Yeah, I was confused. Their [ed25519 crate](https://github.com/RustCrypto/signatures/tree/master/ed25519) says
> Edwards Digital Signature Algorithm (EdDSA) over Curve25519 as specified in [RFC 8032](https://www.rfc-editor.org/rfc/rfc8032).

I didn't follow up on this before, but it does look like the RFC says "Edwards25519" for hte curve, so... yes? But it also seems like ["Curve 25519"](http://cr.yp.to/ecdh.html) might be different from "Edwards25519". I can try to dig a little more to make sure it has the right parameters set. 

That said, the [reverse dependencies of the ed25519](https://crates.io/crates/ed25519/reverse_dependencies) crate seem to include lots of blockchain stuff so I would take that as a context clue that it does what we want.

**Comment by picklenerd** [comment]
`k256` sounds good to me. It's marked as no_std:
https://github.com/RustCrypto/elliptic-curves/blob/master/k256/src/lib.rs#L1

Just to double check, I made a little `#![no_std]` crate locally and added some of the code from one of their benchmarks. It compiled and ran fine.
