### ISSUE TITLE
Implement local method for creation + encryption of signing keys

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#239]
In #234, we introduce methods to create and encrypt a signing key. These methods don't panic, but the signing key is just a unit type. 

- [x] Actually call the method to create a meaningful signing key (should be defined in #235)
- [x] Encrypt the signing key
- [x] Make sure decryption still works
- [x] Add some bad-behavior tests

note on the epic: this is actually only used in the local client version where signing keys are encrypted with the client-side storage key. Maybe we need another epic for that?

**Comment by indomitableSwan** [comment]
This would be nice to implement in the near future, but is not strictly necessary for our next release.

**Comment by marsella** [comment]
I think this is actually all completed in #262. I am not quite sure anymore, but I think this is referring to the `create_and_encrypt` function on `SigningKeyPair`s.

**Comment by indomitableSwan** [comment]
> I think this is actually all completed in #262. I am not quite sure anymore, but I think this is referring to the `create_and_encrypt` function on `SigningKeyPair`s.

I think so, too, but someone should probably double check that all the boxes are ready for checkmarks.
