### ISSUE TITLE
Add remote generation methods

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#242]
The public method for creating new `Secret`s only works for locally (client-side) generation. 

- [ ] Add a new method for remote generation, per [the spec](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/system-functionalities.md#remote-only-secret-generation-and-storage):
> Runs the generate protocol on input `(32, rng, user_id||key_id||"server-generated")` to get a secret `arbitrary_key`

- [x] Fill in the method for remote generation of signing keys.

**Comment by marsella** [comment]
Remote generation of signing keys is already implemented correctly in #262.

@indomitableSwan, I have a memory that we decided to _not_ support remote generation of arbitrary secrets (because the key server cannot do anything with them other than retrieve them, so it's better to only allow them to be stored encrypted). Is that correct? If so, this issue can be closed.

**Comment by indomitableSwan** [comment]
> Remote generation of signing keys is already implemented correctly in #262.
> 
> @indomitableSwan, I have a memory that we decided to _not_ support remote generation of arbitrary secrets (because the key server cannot do anything with them other than retrieve them, so it's better to only allow them to be stored encrypted). Is that correct? If so, this issue can be closed.

I think that's the correct decision at this point in time.

**Comment by marsella** [comment]
Great. Then I will close this, with a reference that the piece we chose not to implement is in the (closed) PR #310.
