### ISSUE TITLE
lock-keeper crate cleanup

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#257]
I've done a first pass on a re-organization plan for the modules.

- [x] `defaults`
  - [x] Rename to `constants` and move all constants here
  - [x] Move client and server specific constants to their respective crates
- [x] Separate `types` into submodules
  - [x] The `types` module contains type definitions that are shared between crates but have little to no logic
  - [x] Move existing types to `operations` submodule
- [x] Move `users` into `types`
- [x] `lib`
  - [x] Move `ClientAction` to `types::operations`
  - [x] Move `RetrieveContext` to `types::retrieve`
  - [x] Move `TestLogs` to `lock-keeper-tests` crate
- [x] Create `infrastructure` module
  - [x] Move `channel`
  - [x] Move `pem_utils`
  - [x] Move `opaque_storage`
- [x] Delete `timeout`

**Comment by marsella** [comment]
`transaction` is part of the high-level API we made ages ago, so I would be fine to wrap it into #253 and remove it from the repo for now.

**Comment by marsella** [comment]
As part of this issue, can we also add module-level documentation for any public modules that don't have docs yet?

**Comment by picklenerd** [comment]
> As part of this issue, can we also add module-level documentation for any public modules that don't have docs yet?

I think that's a great idea.

I would also like to propose that we postpone any discussion about enclave integration until we know exactly what the requirements will be. There will be many more module refactoring passes in our future and we can work enclave integration into one of those.

**Comment by picklenerd** [comment]
I ended up removing most of the unused fields from the server config along with the the constants and dependencies associated with them.
