### ISSUE TITLE
Design transaction approval request communication model

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#26]
A client component (remote or local) can create a `TransactionApprovalRequest` and send it to the key servers for approval. The expected outcome is a `TransactionSignature`. However, sometimes generating the signature might be a long process (involving a multiparty computation protocol, additional requests sent to possibly slow asset fiduciaries, etc.). 

Possible issue: if the client component maintains open channels with the key servers throughout the whole process, they are using up resources (open sockets?). A malicious client could initiate lots of transaction approval requests and cause a denial of service attack, preventing honest clients from opening channels with the servers.

This issue can be closed when we have:
- [ ] A recommendation for a network architecture that is less vulnerable to DOS attacks (or an argument that the DOS attack described above is not worth defending against)
- [ ] A specification for how to build out the architecture in Rust, including any relevant implementation details. For example: config options for timeouts, retries, delay periods, etc. and proposed default values; notes about existing Rust libraries that might be useful; proposed changes to our existing networking tools (dialectic)
- [ ] A new issue or epic with issues to implement the solution

The recommendation and spec can be contained in comments on this issue.

**Comment by indomitableSwan** [comment]
Closing for all the reasons listed above. See also https://github.com/boltlabs-inc/key-mgmt-spec/issues/136.
