### ISSUE TITLE
Design and implement representation of signing authorities

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#27]
Any key with delegated signing authority needs to have a field to describe who the delegated party is. In a simplified instantiation, this party might be the same for all keys, or selected from a list of approved delegated parties (assigned at system setup). In a more complex version, this might be an arbitrary party.

`Delegated` and `Passive` types need to specify who the party is. This issue is complete when

- [ ] There is a type that holds all the information needed to interact with a delegated party
- [ ] There is a way to specify a default value (e.g. in a config file) for the simplified version of the system (where the Service Provider is always the delegated party)
- [ ] There are additional notes in this issue about how to extend the representation to more complex cases with multiple delegated parties

**Comment by indomitableSwan** [comment]
Closing as premature.
