### ISSUE TITLE
Add tracing messages to the server

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#298]
The server is currently doing very little logging. When debugging, this means inserting a bunch of print statements or running `gdb` to figure out what's going on.

The server should make extensive use of `tracing::trace!` messages to report what it's doing. A few examples are listed below but feel free to add more:
- [x] The name of the operation that was called
- [ ] The type of every message sent or received over a channel (this might be possible to put in the channel type)
- [x] The name of each database function that's called.

Additionally, for documentation:
- [x] Provide appropriate developer documentation for the use of logging in our code
- [x] Provide appropriate deployment documentation on where to locate the logs and how to change configuration

**Comment by gatoWololo** [comment]
I really like good logging in code. Using `info!` is a good start, I would personally take if farther and use the other logging verbosities available. This is by convention, but something like:
- **error!**: Report unexpected errors or failures in the system.
- **warn!**: Warn of possible issues that are not necessarily fatal.
- **info!**: For high-level, relevant, events to the execution of the code.
- **debug!**: More verbose, good to have information for debugging purposes.
- **trace!**: Very verbose information that allows you to trace the execution of a program.

Beyond just messages, note that `tracing` crate allows you to set up spans. These spans can carry relevant contexts allowing every message to print additional metadata without having to pass those values around, neat!

**Comment by picklenerd** [comment]
That sounds like a good idea. I'm going to update the ticket to say `trace!` for the general case since I think all of these examples qualify. We can play the rest by ear.

**Comment by jwantz** [comment]
> That sounds like a good idea. I'm going to update the ticket to say `trace!` for the general case since I think all of these examples qualify. We can play the rest by ear.

In a production environment, I'm used to setting log levels no lower than info (sometimes only warn). The debug or trace levels are often used during development or for only a few minutes of execution in a production environment that is being diagnosed in real time. The reason I'm mentioning this in this thread is that I'd like to suggest your second bullet should be at the `info` level at the present time: `The type of every message sent or received over a channel`. In future releases of our product, we may then choose to downgrade those log statements to debug or trace.

**Comment by picklenerd** [comment]
Backtrace is stable! I think we can avoid these extra error logs now as long as we make sure that we have good backtraces for them.
https://doc.rust-lang.org/stable/std/backtrace/struct.Backtrace.html

**Comment by picklenerd** [comment]
Added a new ticket for backtraces:
https://app.zenhub.com/workspaces/bolt-team-60886be9e01f13000e361d92/issues/boltlabs-inc/key-mgmt/343

**Comment by gatoWololo** [comment]
Closed by #380
