### ISSUE TITLE
Add e2e test comparing import input and export output

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#299]
Right now, the export e2e tests only test:
1. Whether we are able to export an existing signing key without any errors.
2. Whether we get errors when trying to export the wrong key ID/type with the wrong function.

Once we add key material to the SigningKeyPair type, and the corresponding Import and Export types are updated, we should update the e2e tests to compare the output of Export with the bytes that we use for Import.

**Comment by indomitableSwan** [comment]
Following up on the PR that mentioned this issue, and I'm not sure I'm following the context entirely. Are we talking about modifying import to return the imported key material in its entirety? If so, I think that's the wrong decision.

I understand that we want to be able to do useful testing here, but in general we don't want import to return the entire imported key to the calling application, just the public portion, don't we? Don't we want to limit the amount of "passing around" of secret material that happens in memory? When we get to integrating this onto actual user devices, I'm also not sure this is what we will want in terms of taking full advantage of a trusted execution environment. Maybe @gatoWololo has some relevant systems-level memory-handling thoughts here.

There are other ways of testing here that would not require passing key material around. e.g., fingerprints.

**Comment by vidyaap** [comment]
For context, I want to compare the raw bytes we pass into import with the bytes we get back from export - the import function just throws out the bytes we pass to it until #262 is merged, so I can't do that yet. Didn't mean to imply any modifications to the return type of import!

**Comment by indomitableSwan** [comment]
> For context, I want to compare the raw bytes we pass into import with the bytes we get back from export - the import function just throws out the bytes we pass to it until #262 is merged, so I can't do that yet. Didn't mean to imply any modifications to the return type of import!

But that does mean that we're keeping the secret material in memory for longer, doesn't it?

**Comment by vidyaap** [comment]
Yes, but this would be in the e2e test code only.

**Comment by indomitableSwan** [comment]
> Yes, but this would be in the e2e test code only.

Thanks for the additional context/explanation!

**Comment by gatoWololo** [comment]
> Maybe @gatoWololo has some relevant systems-level memory-handling thoughts here.

I would have to look more closely at trusted execution environments, e.g. SGX, before being able to say. Intuitively, I agree the less pointers and manipulation we do on secret data the better.

> But that does mean that we're keeping the secret material in memory for longer, doesn't it?

> Yes, but this would be in the e2e test code only.

Would we be keeping the secret material in memory for longer?

I imagine at some point in the future this data would be stored in persistent storage. So if I am understanding what Vidya is proposing correctly: an e2e test that imports a key and later exports a key and compares the bytes. That seems like a very reasonable test and workflow for a client.
