### ISSUE TITLE
Add server-side encrypted storage

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#307]
In the passive / remote generation flow and the import-only-to-server flow, the key server creates (or receives) keys on behalf of the client and puts them in secure storage. The parameters for server-side secure storage of keys are still relatively undefined (see boltlabs-inc/key-mgmt-spec#28), but the rudimentary guidance says
> All data stored by the server MUST be encrypted by a key known only to the server.

At time of writing, this requirement is not satisfied. When the server imports or generates keys, they are transformed into a `PlaceholderEncryptedSigningKeyPair`, which does not actually encrypt the data; it just copies it.

In lieu of completing boltlabs-inc/key-mgmt-spec#28, we should try to implement a simple solution that involves actual encryption. A reasonable first step is to reuse the generic AEAD encryption API we already built for client-side encryption. Rough steps:
1. Update the spec to document initial steps and encryption algorithm, and decide how to store (or derive) the server's encryption key.
1. Define a cryptography API. This should include a type for the server encryption key, including a generation function, and methods to encrypt + decrypt signing key pairs.
1. Update the server-side protocol implementations to use this encryption instead of the dummy `Placeholder`. Update the server setup code to generate the key, if appropriate.
1. Remove all traces of `PlaceholderEncryptedDSigningKeyPair`.

**Comment by gijsvl** [comment]
Important note on this issue: `PlaceholderEncryptedSigningKeyPair` implements `ZeroizeOnDrop` as it contains the plain text key. As soon as it becomes an encrypted version of the key it doesn't need to implement that trait anymore.
