### ISSUE TITLE
Improve filtering for audit logs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#32]
The `retrieve_audit_log` functions for the local and remote clients could use additional server-side filtering to reduce the size of the returned object. 

- [x] Add an optional date range parameter
- [x] Decide if any other parameters are worth adding: We decided on Sept 27 that we will only support the date range for now

Future consideration (not part of this ticket): We will need to handle chunking of response data, such as when the number of filtered rows is too large to send in a single response. We would also have to decide how to make that configurable.

**Comment by vidyaap** [comment]
The date range parameters were covered in the audit event log PR #256
