### ISSUE TITLE
Expand session key to support authenticated sessions

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#327]
The `OpaqueSessionKey` type is currently not usable for anything. We want to use it to enforce an application-layer authenticated, encrypted channel. To do this, we need to implement AEAD encryption and decryption under the session key.

1. Outline an `encrypt` and `decrypt` function on `OpaqueSessionKey`. Check with developers about what message type it should take.
2. Implement `encrypt` and `decrypt` using the generic AEAD abstraction we already have (might have to change the representation of the key type to support this more easily).
3. Check in on whether there should be a further key derivation from the raw session key bytes to the AEAD key. If so, implement that (maybe at creation of the key).
4. Write appropriate tests.

Questions:
- boltlabs-inc/key-mgmt-spec#149 still talks about creating a MAC key (as does [this part of the spec](https://github.com/boltlabs-inc/key-mgmt-spec/blob/develop/systems-architecture.md#opening-the-application-layer-authenticated-channel)). Will we use a MAC in addition to an AEAD, or does the "authenticated" in AEAD handle that?

**Comment by indomitableSwan** [comment]
> The `OpaqueSessionKey` type is currently not usable for anything. We want to use it to enforce an application-layer authenticated, encrypted channel.
> 
> 1. Define an `encrypt` and `decrypt` function on `OpaqueSessionKey`. Check with developers about what message type it should take.
> 2. Implement `encrypt` and `decrypt` using the generic AEAD abstraction we already have (might have to change the representation of the key type to support this more easily).
> 3. Check in on whether there should be a further key derivation from the raw session key bytes to the AEAD key. If so, implement that (maybe at creation of the key).

Check the OPAQUE implementation, but I do not believe any additional steps are necessary here.

> 4. Write appropriate tests.
> 
> Questions:
> 
> * boltlabs-inc/key-mgmt-spec#149 still talks about creating a MAC key (as does [this part of the spec](https://github.com/boltlabs-inc/key-mgmt-spec/blob/develop/systems-architecture.md#opening-the-application-layer-authenticated-channel)). Will we use a MAC in addition to an AEAD, or does the "authenticated" in AEAD handle that?

We do not need the additional MAC.
