### ISSUE TITLE
Create a `LockKeeperResponse` type to return from the client

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#329]
Client API functions currently return their result types directly. For example, the `export_signing_key` function returns a `Result<Export, LockKeeperClientError>`, so you call the function and you expect to get an `Export` back. 

In a traditional client/server system, the client gets network responses back from a server. These network responses can include headers with useful metadata about the request or response. Since our client abstracts over the network requests, we don't have a way to include useful metadata.

One piece of metadata that would immediately be useful is an ID assigned to each request. This ID could be used to filter audit events or during troubleshooting to find server logs associated with a particular request. Being able to filter audit logs by request should make it easy to solve #317 where we're bumping up against our assumptions about the ordering of audit events.

The proposed type would look something like this:

```rust
pub struct LockKeeperResponse<T> {
    pub data: T,
    pub request_id: RequestId,
    // Any future metadata
}
```

Metadata could also go into its own type just to keep things clean.

The return signature for `export_signing_key` would be updated to `Result<LockKeeperResponse<Export>, LockKeeperClientError>`. This is ugly, but we could define a type alias to make it nicer:

```rust
pub type LockKeeperResult<T> = Result<LockKeeperResponse<T>, LockKeeperClientError>
```
This would give us a return signature of `LockKeeperResult<Export>`.

One big benefit of this approach is that it would allow us to add more metadata in the future without breaking the return types of all of our API functions.

**Comment by gatoWololo** [comment]
I agree with everything you stated here. I think this the right way going forward.

My one comment on the type:
```rust
Result<LockKeeperResponse<Export>, LockKeeperClientError>.
```
I agree it would be good to make it nicer. I'm not sure about:
```rust
pub type LockKeeperResult<T> = Result<LockKeeperResponse<T>, LockKeeperClientError>
```
I think it is useful to have the Result be obvious at the top level instead of "hidden" behind the type alias. I like:
```rust
type Result<T> = std::result::Result<T, LockKeeperClientError>
fn export_signing_key(...) ->  Result<LockKeeperResponse<Export>>
```

Basically the type alias + Result pattern.

**Comment by picklenerd** [comment]
Yeah that makes sense. It would probably be really confusing to get the result type back expecting the inner data.

**Comment by gatoWololo** [comment]
@marsella @indomitableSwan I think we wanted to get general thoughts on this before moving forward with it?

**Comment by marsella** [comment]
This seems fine to me as long as we're careful to not throw everything into the metadata. This feels like a bit of client-side session management?

We will need a session ID for communications between client and server so the server can figure out which session key they should use to decrypt the body of networked messages. I don't think that ID needs to be secret, so we might be able to use it as the request ID -- if I understand correctly, you're saying if there's a client-side failure, we/someone might want to cross-reference that with server-side logs to see what exactly went wrong?

**Comment by picklenerd** [comment]
Yep it should make it significantly easier to troubleshoot client errors. It will also make it possible to match audit events to requests during integration tests.
