### ISSUE TITLE
Update CONTRIBUTING.md to reflect TODOs

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#33]
There's a section of `CONTRIBUTING.md` about inline issues / TODOs and how they're linked to GitHub issues. This section also has some notes about the different types of modifiers that describe the context / type of issue. Update the descriptions of modifiers to make sure they correctly capture the different types of issues we want to highlight inline.

**Comment by marsella** [comment]
I think this might be done now with #82. I vote to close.

**Comment by indomitableSwan** [comment]
Agreed with previous comment.
