### ISSUE TITLE
Add authentication tests

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#340]
With #328 merged, we have basic authentication in place. This means that it is now possible for the server to return authentication error. We need e2e tests to cover authentication.

This will be a little bit tricky because there's no way to get a client without authenticating. We need the expiration time for sessions to be short enough to trigger errors during integration tests. The easiest way to solve this would be to add session expiration time to the server config so that we can set a short expiration time for e2e tests. Balancing this with testing normal authenticated operations will require some clever design.

These test cases should be covered at a minimum:

- [ ] Register does not return an session error
- [ ] Authenticate does not return a session error if the user has no valid session
- [ ] Authenticate does not return a session error if the user has an existing valid session
- [ ] All other operations return a session error if the user has no valid sessions
- [ ] All other operations do not return a session error if the user has a valid session

Additionally, we are re-authenticating with each operation in the current test cases. These test cases should be updated to authenticate once as a separate step and re-use that authentication for additional tests. This will ensure that we have good coverage for the normal authentication flow.

- [ ] Update existing test cases to authenticate once and rely on existing sessions for remaining operations.

**Comment by gatoWololo** [comment]
> We need the expiration time for sessions to be short enough to trigger errors during integration tests. The easiest way to solve this would be to add session expiration time to the server config so that we can set a short expiration time for e2e tests

Would it make sense to add an "invalidate key" command to the client? This would be an operation just like any other, which would ask the server to invalidate the current session key. This would allow the client/server testing to have fine-grained control of when keys are invalidated for testing purposes.

Relying on timing for expiration sounds more difficult and brittle. (I do realize this would go slightly against the spirit of e2e tests)

**Comment by picklenerd** [comment]
I really like that idea as a general feature. It would let clients declare that they're done with their session and prevent anyone from re-using it. It wouldn't help us test timed key expiration, but the unit tests already do that so I don't think it matters.

**Comment by picklenerd** [comment]
After some careful consideration, we've come up with a name for this complex and unique command.

"logout"
