### ISSUE TITLE
Add `Backtrace` field to error variants

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#343]
Backtraces were stabilized in Rust 1.65. We should update our error types to support them. 

See: https://docs.rs/thiserror/latest/thiserror

**Comment by gatoWololo** [comment]
We should have a conversation about this at some point. It is not entirely clear what our procedure for capturing and using backtraces would look like. It looks like they're [expensive](https://doc.rust-lang.org/stable/std/backtrace/struct.Backtrace.html#method.capture) to capture.

So it would be good to design how we envision using them, propagating them, etc.

**Comment by picklenerd** [comment]
Looks like you still need the `RUST_BACKTRACE` env var set to incur the expense so I think we can put them everywhere as suggested in those docs.
