### ISSUE TITLE
Application Sessions for Key Server

### ISSUE THREAD

**Issue by LordQ1** [boltlabs-inc/key-mgmt#351]
Please refer to #364  for a high level overview of Application Sessions (or LockKeeper Account Sessions). It is acceptable for the proposed terminology (e.g., Application Session) to be refined/reworked during the design and development of Session Management.

Tasks:

1. Document a design for application session management on the Key Server, to include, but not limited to:
- Data elements in the object model (for example: session_id, user_id, creation_timestamp, session_key_id, nonce)
- Session lifetime (and potential state changes)
- Persistence (if any)
- Expiration handling
- Documentation of concerns and future thoughts
2. Peer review of design, including answers to the following questions:
- How far do we take the approach in the current release (e.g., phased approach)?
- Are there any security concerns or constraints to be addressed?
- Do we have concerns around caching and/or availability at this point?
3. Implementation of the proposed design on the Key Server
4. Appropriate unit tests that include expiration and clean up of sessions

**Comment by LordQ1** [comment]
For this release, we are not concerned with subsessions

**Comment by picklenerd** [comment]
#385 was spit off of this so I distributed the estimate to both tickets.
