### ISSUE TITLE
Update Export/Master key API

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#356]
The current cryptography API assumes that a client will maintain access to their export key across the lifetime of their session, and use it to re-derive the master key whenever necessary.

The correct behavior is to derive the master key as soon as possible (e.g. during registration/authentication), then drop the export key. The master key should be the key held across the lifetime of a session.

- [x] Maybe take out the `OpaqueExportKey` type entirely and have a function that goes straight from opaque_ke export key type to `MasterKey`.
- [x] Update `decrypt_storage_key` function to take a master key instead of an export key
- [x] Move the `create_and_encrypt_storage_key` method to be on `MasterKey` instead of `OpaqueExportKey`
- [x] Update the `LockKeeperClient` to hold a `MasterKey` instead of export key and update client methods (side question: why does `handle_create_storage_key` not take `&self`?)
- [x] Revisit database tests that involve export keys

Notes for the future: Currently, we use the `MasterKey` directly for encrypting the storage key. If we have more client-side cryptographic operations in the future that require key material, we'll want to apply a KDF to `MasterKey` with some relevant domain separation to create separate keys for each application.

**Comment by gijsvl** [comment]
To answer your side question: The `handle_create_storage_key` is called from within a static function, if it would actually take `&self` we would have to create a `LockKeeperClient` object at that point.
