### ISSUE TITLE
Move config file tests into unit tests

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#361]
The current server and client config tests live in the `lock-keeper-tests` crate since they depend on external state in the `dev` directory. These files don't always exist so we can't depend on them in unit tests.

We can put static certs and keys somewhere in the repository so that they can be referenced in unit tests. We should be able to reference them from unit tests using `CARGO_MANIFEST_DIR` as the base path. This should allow us to move these into the unit tests.

Github will probably complain if we commit private keys so we may also need a way to make it stop complaining.

**Comment by gatoWololo** [comment]
Instead of using a file, would it make sense for the static certs and keys to be constant variables in some unit test Rust file? Or is that dumb?

**Comment by picklenerd** [comment]
I'm totally fine with that. We could also `include_str!` some files.

**Comment by gatoWololo** [comment]
Right. The reason I suggested having in the code was to avoid github complaining about certs and keys in version control, but `include_str!` is definitely cleaner!

**Comment by picklenerd** [comment]
My guess is that it would probably still have a warning based on the contents of the string but it's worth investigating!

**Comment by picklenerd** [comment]
We've decided to leave the tests where they are.
