### ISSUE TITLE
Clean up server tasks in `Makefile.toml`

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#368]
We have a large number of `cargo make` tasks to start the server. With the addition of mutual auth, I added two new tasks for each case do the number has grown significantly.

It would be nice to parameterize these. It's possible to forward arguments from cargo make to the commands it runs, but I'm not sure if there's a way to dispatch to other commands based on the the arguments.

If we can't parameterize them this way, it would at least be useful to make the tasks with the shortest names start both servers, since this is what's required to run the full test suite.

**Comment by gatoWololo** [comment]
> If we can't parameterize them this way, it would at least be useful to make the tasks with the shortest names start both servers, since this is what's required to run the full test suite.

I definitely find myself forgetting all the names of the tasks. I think `cargo make` is useful as a dev tool when working on the repo. I would suggest keeping the most useful, default commands.

Other commands can always be fully written out if needed.
