### ISSUE TITLE
Select, implement and document logging package/crate

### ISSUE THREAD

**Issue by jwantz** [boltlabs-inc/key-mgmt#369]
**Overview:** Refer to #347 for the proposed improvements to Key Server logging. This ticket will be used to track the selection, implementation and associated documentation of the logging package/crate.

- [x] Select a logging library/crate that supports:
- - Different types of appenders (e.g., file, stream, console, syslog)
- - Different log levels (e.g., debug, info, warn, error, etc)
- - The ability to provide different configuration and appenders for distinct components in the software framework (e.g., network communications vs message processing vs persistence)
- [x] Determine whether we need to implement an abstraction layer. This is only needed in the case where we might need to swap out logging libraries or if we anticipate others (users of our open source) wanting to swap out logging libraries.

**Comment by gatoWololo** [comment]
@vidyaap @picklenerd @jwantz @gijsvl

I have reviewed the [`tracing`](https://docs.rs/tracing/0.1.37/tracing/index.html) crate and associated ecosystem to make sure it matches all our needs.

The `tracing` crate provides the core tracing functionality. This includes different the different tracing levels for `events` (specific moments in time) we are used to: info, warn, error, trace, debug. Additionally `tracing` has a concept of `span`s, this is the current context that events are happening under, e.g. the `foo` function span. Spans allow us to attach relevant context to events. Spans, additionally, spans have have arbitrary subspans. This creates a hierarchy of contexts which are attached for events. So a message like `trace!("Failed to fetch username: {}", username) would normally produce a log message like:
```
[Timestamp][trace] Failed to fetch username omar.
```
With appropriate spans set up the same trace message would look like:
```
[Timestamp][trace] {user_id=ID}{operation=retrieve}{other relevant data fields}[Operation::handle_request] Failed to fetch username omar.
```

Here is a summary of the crates we will use:
- `tracing`: "A scoped, structured logging and diagnostics system." `tracing` provides the types and implementation for events and spans, and the definition for `subscriber`s. As Spans and Events occur, they are recorded or aggregated by implementations of the `Subscriber` trait.
- `tracing_futures`: Futures compatibility for `tracing`.
- `tracing_subscriber`: "Utilities for implementing and composing `tracing` subscribers.
- `tracing_appeder`: " Provides utilities for file appenders and making non-blocking writers."
- `tracing_log`: "Adapters for connecting unstructured log records from the log crate into the tracing ecosystem."

`tracing` and spans work particularly well with async code like ours. Spans allow us to determine events that happened in a specific future (assuming you have set a per-future span) so you can filter log events relevant to a specific future. `tracing` has special support via the `tracing_futures` crate for handling asynchronous spans. I plan to use extensive use of the [`instrument`](https://docs.rs/tracing/0.1.37/tracing/attr.instrument.html) macro for defining spans.

> Different types of appenders (e.g., file, stream, console, syslog)

We can use different appenders, the `tracing_appeder` crate provides utilities for file and non-blocking writers.

> Different log levels (e.g., debug, info, warn, error, etc)

This is included by default in the `tracing`. 

> The ability to provide different configuration and appenders for distinct components in the software framework (e.g., network communications vs message processing vs persistence)

`tracing_subscriber` provides the concept of `Layer`s and `Filter`s. `Layer`s provide a "composable abstraction for building Subscribers". A Layer defines a particular behavior for collecting trace data. "In addition, the `Filter` trait defines an interface for filtering what spans and events are recorded by a particular layer". We can combine this with the [`target`](https://docs.rs/tracing/0.1.37/tracing/struct.Metadata.html#method.target) field on events to allow different layers to only capture specific targets we are interested in, e.g. opaque, operation, database, etc.

> Determine whether we need to implement an abstraction layer. This is only needed in the case where we might need to swap out logging libraries or if we anticipate others (users of our open source) wanting to swap out logging libraries.

The `tracing_log` crate allows us to intake logging events from the `log` ecosystem and turn them into events with spans that `tracing` can process. By default, `tracing` allows us to output our events as `log` events so a client of our libraries can process our events. E.g. logging messages from the client library.

I know this sounds a little complicated! However, devs (us) will only have to add event messages via the event macros and define new spans on new, relevant functions. It will be pretty chill.

I will start working on this, but lmk if you have any questions or concerns. If this sounds good with everyone, I can close this ticket and start working on the follow-up ticket: #298.

**Comment by picklenerd** [comment]
This sounds fantastic! Thanks for this awesome write up.

**Comment by gatoWololo** [comment]
If there is no more feedback on this, I can mark it as closed and continue the impl work!
