### ISSUE TITLE
Select open source persistent storage product for development

### ISSUE THREAD

**Issue by LordQ1** [boltlabs-inc/key-mgmt#372]
**Background:** Refer to #346 for the motivation behind this ticket, as well as the related tickets to the Epic.

**Tasks:**

1. Brief survey of open source persistent storage products that will meet our needs for the LK Key Server
1. Select a viable product that we will use for our reference implementation
1. Hold a peer review and discussion around the product selection

**Comment by gatoWololo** [comment]
Per the ticket I wanted to hold a conversation tomorrow during our work session to see if there are any lingering concerns about the use of this library. Here, I will answer a few questions and concerns:

We are looking at using `sqlx` with postgreSQL.
- sqlx supports different SQL database backends: postgreSQL, mySQL, SQListe, and MSSQL. So we could always move away from post postgreSQL if needed. Or easily swap out the database implementation if a customer requires it.
- sqlx allows for compile time checking of the queries by connecting to the running instance of the DB and ensuring all the types and schema matches. This is given via a URL so the DB can be running local, remote, or in a docker container.
- We don't need a running database for compile-time checks to work. We can set up a *.json file which can be used instead which contains and schema and other information. This is useful for development not involving the DB. This json file can be auto generated by the `sqlx-cli` utility. Which can be integrated to the CI to auto update if any changes are made to the DB schema.
- sqlx can automatically map query results to Rust user-defined domain types. There is a couple of ways to do this. The `query_as!` macro seems to be the best way to do this, as it does not require a proc macro on the types. This gets around a concern of having the proc macro slowly creep into all our types. I think we have done a good job thanks to our `DataStore` abstraction of separating the DB types from the Rust types used in the server (which are DB schema agnostic). So I don't think this will be an issue.

Lmk if you have any further questions or concerns.

**Comment by gatoWololo** [comment]
If there are no further comments. We can mark this as completed :)
