### ISSUE TITLE
Integrate and test persistent storage product with Key Server

### ISSUE THREAD

**Issue by jwantz** [boltlabs-inc/key-mgmt#378]
**Background:** Refer to #346 for the motivation behind this ticket, as well as the related tickets to the Epic. This ticket is heavily dependent upon the vendor product selection referenced by #372.

**Tasks:**

1. Integrate selected vendor product with our database abstraction layer (also refer to the dependency upon #372)
1. Perform developer testing and ensure that all pre-existing unit tests pass
1. Provide any necessary documentation for developers to install/deploy the selected product with our Key Server
1. Suggest the types of testing that should be performed in the future to ensure that another selected vendor product could be tested as "compliant" with our Key Server

**Comment by gatoWololo** [comment]
Closed by #406
