### ISSUE TITLE
Separate database config from server config

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#392]
We currently have the database configuration built into the server configuration. This makes sense for the `docker compose` based local workflow, but it doesn't make sense in a normal server environment with an independent database.

The current config looks like this:

```rust
pub struct DatabaseSpec {
    pub mongodb_uri: String,
    pub db_name: String,
}
```

We may need to maintain the URI in the server config, but the `db_name` is an implementation detail of the database. Our `lock-keeper-mongodb` reference implementation should have its own config that contains this field and possibly also the table names. This config should be loaded somehow when we instantiate the database connection.

The server config should be reduced to the minimal amount of configuration necessary to connect to an arbitrary database. This might be difficult to make assumptions about right now, but I feel like a full URI is the safest bet. We should meet up and discuss a general strategy for configuring all of our plugin services before this is implemented.

**Comment by vidyaap** [comment]
Follow up from a working session:
- This ticket should include moving the session cache config information as well.
- We decided to try creating a config for the key server binary that holds config information/file paths for the various pluggable services. This would mean creating a new binary for large changes - like swapping the type of a service used - to point to the correct config files and create the appropriate Rust types. Switching between different instances of the same type of service (e.g. two different SQL databases) should be possible with the same binary.
