### ISSUE TITLE
Implement client API with store/retrieve functionality

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#4]
Define an API for the client library that allows them to store a secret and retrieve it. Maybe create a command-line interface to call the library functions? Or just do a simple binary `main` that calls `store` and `retrieve` in succession. Or just don't make a binary yet.

Add server functionality to respond to `store` by holding the secret in memory; and respond to `retrieve` by sending it  and return it on request.back.

Expand protocol session type to reflect the data being sent between the parties. Define a simple data type to hold a secret (this will probably be replaced in the long term with a `Secret` type from a cryptography library).

Add an integration test to call `store` and `retrieve` and confirm that the returned result matches.

**Comment by indomitableSwan** [comment]
@marsella With respect to the server tests, can you expand the positives and negatives for each testing approach? Is one approach going to be better for benchmarking, testing concurrency, etc? Will changing our mind later be difficult?

**Comment by marsella** [comment]
@indomitableSwan Per discussion in the meeting today, we decided to rewrite this issue and others to include the tests they need to support directly in the original issue, instead of having a separate issue. But to answer your question:

If we use the built-in integration testing framework for Rust, each test will have to create its own server to interact with. Pros: better infrastructure (e.g. for tagging tests, for selecting certain tests to run, for running tests in the CI). Relatively easy to switch to a custom harness later, since we'll have all the logic of the tests themselves written. Cons: lots of wasted work creating single-use servers, we might have to be careful about e.g. ports that they use to keep tests parallelizable.

If we make our own testing harness, we'll be able to make a single server that is reused for all tests. Pros: more efficient use of server code, tests will likely run faster. Cons: more dev work up-front, not clear how much performance gains we get, will have to build a bunch of infrastructure to make it easier to use (e.g. filtering tests by name), will have to manually build in parallelization.

I am not sure about benchmarking. The custom test harness would make it easy to do similar benchmarking across all tests, but I also think that Rust's standard test infrastructure comes with some benchmark features that haven't explored yet. 

Overall, I think we should stick with the slightly less efficient standard Rust testing infrastructure, and only build a custom test harness if we come up with a more pressing scenario that requires the additional work.

**Comment by indomitableSwan** [comment]
I'd like to advocate that we make a dedicated epic for API implementation, and not get ahead of ourselves by assuming we are ready to implement `store` and `retrieve`.

In particular, I think we should define a forward-looking API that anticipates the full functionality of our library, not just the first iteration.
