### ISSUE TITLE
Client auth test sometimes fails in CI

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#402]
The `client_auth_required_not_provided` test case sporadically fails in CI. It seems to be a race condition.

See: https://github.com/boltlabs-inc/key-mgmt/actions/runs/3675356392

The error it's returning is a `ChannelClosed` error which seems to be coming from `tonic`. This test calls the health check endpoint which is a normal RPC endpoint that doesn't use any of our channel infrastructure.

**Comment by picklenerd** [comment]
I have't seen this issue come up since the environments PR was merged. I'm going to close this for now. We can re-open it if this is still a problem.

**Comment by picklenerd** [comment]
This is still happening

https://github.com/boltlabs-inc/key-mgmt/actions/runs/3878805354/jobs/6615329944

**Comment by picklenerd** [comment]
I updated the test to accept any error. I suspect that this is occasionally triggering an alternate code path because it's a TLS error but I have no evidence to back this up.

**Comment by LordQ1** [comment]
Hasn't been seen in a while, closing again.
