### ISSUE TITLE
Ensure that all audit events are tied to an account

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#413]
We create audit events for registration even if registration fails and an account is not created. This means that audit events may or may not be associated with an actual account and complicates the database mapping between audit events and accounts.

In the software developer working session, we discussed the merits of having audit events for failed registration. This seems like something that should be logged in the server for security purposes, but not recorded as an audit event. It seems unlikely that anyone would perform audits on non-existent accounts.

We are proposing to remove registration audit events that are created before the account is created, and replacing the `account_name` field in the database with `account_id` which maps directly to the (soon to be created) `accounts` table.

We would like to discuss this potential change with the rest of the team and @indomitableSwan in particular.

**Comment by indomitableSwan** [comment]
I don't have any objections to this change.

We may want to consider including reregistration attempts in a given user account's audit log, i.e., say someone tries to register an account with the same client identifier as for an existing account.

Not sure what the right answer here is though, so perhaps it's sufficient to handle this circumstance via the separate security logging & associated processes (which might include informing the user of suspicious activity).
