### ISSUE TITLE
Logging not capturing span variables.

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/key-mgmt#416]
I realize now I was wrong about how the `instrument` macro works. We are not recording variables as part of the `span` as previously thought. For example:
```rust
#[instrument(skip_all, err(Debug), fields(account_name))]
async fn operation(
        self,
        channel: &mut ServerChannel<Unauthenticated>,
        context: &mut Context<DB>,
    ) -> Result<(), LockKeeperServerError>
```
By default, `instrument` tries to record all arguments to this function. So we use the `skip_all` option to avoid this. Then we manually opt in to recording the `account_name` by specifying `fields(account_name)`.

This does not work as expected. The `fields(account_name)` is incomplete and will not record the value of `account_name`; this merely declares the field for our logger.

We either need to call our `record_field` function at the very beginning, e.g:
```
record_field("account_name", account-name);
```
Or write the instrument macro as:
```rust
#[instrument(skip_all, err(Debug), fields(account_name=?account_name))]
```
The `?` tells `tracing` to use the `Debug` impl of this type. This can get a little hairy:
```rust
#[instrument(skip_all, err(Debug), fields(account_name=?account_name, event_type=?event_type, options=?options))]
```

The other options is to stop using the `skip_all` macro manually list the arguments we want to skip. We just have to be careful to skip every field that should not be included.

To close this ticket:
- [x] Ensure all instances of `instrument` macro are correctly written.
- [x] Update README about logging to reflect the correct way to do it.

**Comment by picklenerd** [comment]
I think I'd be ok with manually skipping for readability. We just have to be careful with new functions.
