### ISSUE TITLE
Add unstable rustfmt options

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#42]
I think it would be a good best practice to enable [the nightly `rustfmt` option to wrap comments](https://rust-lang.github.io/rustfmt/?version=v1.5.0&search=#wrap_comments). 

We might not want to enable it in the CI, because we might occasionally have exceptions that need to be maintained manually (e.g. if the wrapping breaks a link or a table). But maybe we should enable until there's a specific thing that breaks.

----
Another unstable option we've discussed is to set [the import granularity](https://rust-lang.github.io/rustfmt/?version=v1.5.0&search=#imports_granularity) to `Crate`.

**Comment by marsella** [comment]
Is this closed by #106?

**Comment by picklenerd** [comment]
Yep!
