### ISSUE TITLE
Use `account_id` for queries into the Secrets table.

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/key-mgmt#442]
We would like to use `Accounts.account_id` for queries into the `Secrets` table. Currently we are using `account_name` since that's readily available and that's how the current `DataStore` interface is implemented.

Changing the interface for the relevant methods (e.g. `get_user_secret`) is straightforward. The more difficult part is ensuring the `account_id` is readily available to the caller.

A non-solution would be to join the Secret and Account table and still use the `account_name` for lookups. This would defeat the purpose as we would still be doing the lookup using a string (`account_name`). We want to make sure the mapping from `account_name` to `account_id` is done once (we have suggested doing it after authentication) and keeping the `account_id` for the lifetime of the session. The `account_id` could be kept in the session cache maybe.

Relevant ticket #438. @picklenerd understands and has thought more about how the implementation of this would look like.

Tasks:
- [ ] Use `account_id` for queries on `Secret` table.
- [ ] Add foreign key constraint on `account_id` for `Secret` table.

**Comment by picklenerd** [comment]
Closed in #438
