### ISSUE TITLE
Foreign Key Constraint on AuditEvent.key_id

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/key-mgmt#443]
## Goal
We would like to have a foreign key constrain on `AuditEvent.key_id` so every `key_id` reference in our audit events is guranteed to point to a valid key. This does not currently work as our code does not have a way of ensuring only valid key IDs (i.e. key IDs present on the Secrets table) are included in our audit events.

## Problem
We cannot simply add the foreign key constraint. This is because a few of the export tests fail. For example, `cannot_retrieve_fake_key` attempts to fetch a key that does not exists, this creates an audit event with the fake key ID, the database complains this breaks referential integrity since the key does not appear in Secrets.

Notice this problem is not an artifact of our tests, but a general problem we need to consider how to handle: How do we handle audit events for invalid keys? 

Digging through the relevant code, we might need to change how we handle recording audit events. Currently, any server operation calls `audit_event`:
```rust
match self.operation(&mut channel, &mut context).await {
                    Ok(()) => {
                        info!("This operation completed successfully!");
                        audit_event(&mut channel, &context, EventStatus::Successful).await;
                    }
                    Err(e) => {
                        info!("This operation completed with an error!");
                        handle_error(&mut channel, e).await;
                        audit_event(&mut channel, &context, EventStatus::Failed).await;
                    }
                }
```
Our `audit_event` function merely attempts to record an audit event based on the return value of the operation and the context available to it: `.create_audit_event(request_id, account_name, &context.key_id, action, status)`. It does not care if the key is valid, or the result of the operation.

How do we want to handle this?

**Comment by LordQ1** [comment]
Do not work. Review this ticket at a later date to see if it is workable/still valid/if a solution is clearer.

**Comment by LordQ1** [comment]
This was marked 'Wont Fix' due to discussion in the Thursday 1/19/2023 Dev Meeting
