### ISSUE TITLE
Nitro enclaves can't handle multiple requests because of a File descriptor error

### ISSUE THREAD

**Issue by leboiko** [boltlabs-inc/key-mgmt#494]
While loadtesting the new Nitro enclave deploy we stepped in an error: `too many open files`, and that indicates that the operating system has reached the maximum "open files" limit and will not allow applications to open any more files. That error makes the enclave panic, and that's undesirable. We believe that this is a configuration problem, such as setting correct ulimits, but this requires investigation. 

A/C: Fix the issue with `too many open files` on Nitro enclaves.

**Comment by LordQ1** [comment]
Was written in the wrong repo.
