### ISSUE TITLE
Generate fixed set of keys and certs

### ISSUE THREAD

**Issue by picklenerd** [boltlabs-inc/key-mgmt#503]
We currently generate new certs and encryption keys every time we start the server. We originally did this to have a safety check that our systems didn't rely on anything hardcoded to a particular cert. This setup can be very inconvenient when you start and stop servers frequently. If you use a cargo make task that runs the generation script, it'll break your whole local install since the keys won't match anymore.

I think we're pretty safe from hardcoding issues at this point, so we should move to a fixed set of certs and keys for local development.

- [ ] Remove `dev/remote-storage-key/gen` and `dev/test-pki/gen` from `.gitignore`
- [ ] Remove the `certs` task from all other task dependencies in `Makefile.toml`
- [ ] If Github complains about key material being committed to the repo, find a way to disable the warning
- [ ] (optional) Figure out a way to prevent these keys and certs from being used in production

**Comment by gijsvl** [comment]
My two cents: if we go through with this, that last task is very much not optional, but a requirement in my opinion. Another option: couldn't we make the generation of these keys more optional in the sense that if they already exist, we don't generate them again (with an option to force regeneration of keys). In that way we still don't have to check them in into the repo, but we don't generate them every time we restart the server.

**Comment by picklenerd** [comment]
If we go with checking that certs exist:

- [ ] Update README with common certificate errors and instructions for how to generate new ones.
