### ISSUE TITLE
Cannot setup the project in local

### ISSUE THREAD

**Issue by nil96** [boltlabs-inc/key-mgmt#506]
I downloaded and ran the project locally using the command (cargo run --bin key-server-cli ./dev/config/local/Binary.toml).After that I tried to do health check gRPC call but got below error

**Error**
  2023-04-12T15:29:27.634398Z ERROR lock_keeper_key_server::server::service: connection error: unexpected end of file
    at lock-keeper-key-server/src/server/service.rs:97

Error ScreenShot:
<img width="1792" alt="Screenshot 2023-04-12 at 9 03 44 PM" src="https://user-images.githubusercontent.com/9780484/231508383-68b5cf9e-3b4b-4a23-920f-58a6af3613b9.png">

BloomRPC ScreenShot for making the call:
<img width="1329" alt="Screenshot 2023-04-12 at 9 05 57 PM" src="https://user-images.githubusercontent.com/9780484/231508820-7d1256f8-843a-4449-bd78-28dc73735164.png">

Env:
rust version : rustc 1.68.0 (2c8cc3432 2023-03-06)
Docker version: Docker version 20.10.6, build 370c289
Mac version: 12.2 (21D49)

**Comment by LordQ1** [comment]
We believe that this is because the user did not use the proper SDK.
