### ISSUE TITLE
Implement key-value storage for opaque auth information

### ISSUE THREAD

**Issue by gijsvl** [boltlabs-inc/key-mgmt#52]
Opaque authentication information is some information that needs to be stored for each user upon registration in order to authenticate later. This information is basically key/value information, where the key is the user's id, and the value is some serialized byte information. We might want to harden this storage somewhat, e.g. SGX or any other secure storage?

Note, the current implementation is a flat file that gets created for each user in the `opaque_path` folder, this parameter can be set through server configuration. The filename is the user's id, the content of the file is the required opaque authentication value.

**Comment by vidyaap** [comment]
@indomitableSwan Can we close this since the user's opaque info is stored in the database?

**Comment by indomitableSwan** [comment]
> @indomitableSwan Can we close this since the user's opaque info is stored in the database?

Yes.
