### ISSUE TITLE
Reduce CI Times

### ISSUE THREAD

**Issue by gatoWololo** [boltlabs-inc/key-mgmt#605]
CI times for the Lock-Keeper repository seem reasonable but we should see if there is some low-hanging fruit we can address for better times.

Task: Reduce CI execution.

**Comment by jrdngr** [comment]
At the moment we're running tests 3 separate times in series for the three different types of environments we have set up. These environments were set up based on some early designs that are no longer relevant. We can get a significant speedup by simply disabling the tests for two of them.

**Comment by jrdngr** [comment]
Results are in, removing the extra 3 environments from testing saves us 1 minute and removing them from Docker saves us an addition 10 seconds!

This brings our total CI time down from around 12 minutes to around 11 minutes!

**Comment by LordQ1** [comment]
Per Omar: Nothing more to do here; we have other Ci improving tickets.
