### ISSUE TITLE
Spike: Adding --key-id Argument to kmstool-enclave-cli Decryption Operation

### ISSUE THREAD

**Issue by FF-agonzalez** [boltlabs-inc/key-mgmt#609]
ToB Issue 22

We need to create a spike ticket to investigate and address the issue related to adding the --key-id argument to calls to the kmstool-enclave-cli decryption operation.

This spike originates from the fact that we have already tried to implement this in an existing PR but with the current version of the enclave it is not as easy as adding the flag as the recommendation indicates. We should check if we should update the kms tool or find some workaround to reach the final goal.

**Comment by LordQ1** [comment]
Despite the ToB label this is not a must have for the Dec6 deadline; it is T3.

**Comment by LordQ1** [comment]
Despite the ToB label this is not a must have for the Dec6 deadline; it is T3.
