### ISSUE TITLE
Implement "generate and store secret"

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#64]
This implementation will work with arbitrary secrets - that is, the secret material is arbitrary bytes. The flow can be found [here](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/cryptographic_flows.md#generate-and-store-a-secret).

This implementation will happen in two rounds
1. Implement the flow while using unimplemented cryptographic function calls. e.g., to create a secret, call a `generate_arbitrary_secret` function that isn't yet implemented; encryption and hashing can also be abstracted at this stage.
2. Implement the underlying cryptographic functions, e.g., `generate_arbitrary_secret` function. A cryptographer should do this step.

~Eventually, we will need to add the step of verifying that the calling app passed an open, authenticated session with its request as well, before generating the secret.~

NB: This ticket references "local generation of a secret with remote backup", rather than "remote-only secret generation & storage".

**Comment by marsella** [comment]
I was incorrect in my previous comment! This flow doesn't involve communication with the key server.

**Comment by indomitableSwan** [comment]
Include implementation of `retrieve_storage_key` helper in this epic. @vidyaap

**Comment by indomitableSwan** [comment]
This is complete. There is some ongoing testing hardening in #216, but this task does not have to be done as part of this epic.
