### ISSUE TITLE
Implement "storing a secret" flow for one key server

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#65]
This implementation will work with arbitrary secrets. The flow will be defined by boltlabs-inc/key-mgmt-spec#8. This will involve the local client storing a secret with the key server.

We'll implement this in two rounds
1. Implement the basic flow and any supporting infrastructure, but leave cryptographic functions empty (e.g. encryption, ID generation)
2. Implement the cryptographic functions

~Eventually, we will need to add the step of verifying that the calling app passed an open, authenticated session with its request as well, before passing the secret on to the key server.~

**Comment by indomitableSwan** [comment]
Closing for same reasons as in https://github.com/boltlabs-inc/key-mgmt-spec/issues/8#issuecomment-1191673325
