### ISSUE TITLE
Implement "retrieve a secret" workflow for one key server

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#66]
This implementation will work with arbitrary secrets.  The flow will be defined by boltlabs-inc/key-mgmt-spec#12 and will involve the local client retrieving a secret from the key server.

We'll implement this in two rounds
1. Implement the basic flow and any supporting infrastructure, but leave cryptographic functions empty (e.g. decryption)
2. Implement the cryptographic functions

~Eventually, we will need to add the step of verifying that the calling app passed an open, authenticated session with its request as well, before passing the secret on to the key server.~

**Comment by marsella** [comment]
I think #71 and #73 should mutually depend on defining the (dialectic-style) protocol that will be defined in boltlabs-inc/key-mgmt-spec#12. That might benefit from being its own issue / PR. Did you imagine doing that as you go on #71/#73?

**Comment by indomitableSwan** [comment]
This is complete. There is some ongoing testing hardening in #216, but this task does not have to be done as part of this epic.
