### ISSUE TITLE
Define types related to generation/storage/retrieval of secrets (no-crypto version)

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#68]
These 3 flows will work with similar/the same types. There should be a types for:
- Representing the secret material as a wrapper around some bytes
    - for now, this could potentially be the `KeyMaterial` wrapper type made for the key import/export functionality, see #49
- Reporting errors that happen during each of the 3 flows back to the calling app

**Comment by picklenerd** [comment]
This work will happen in the tickets under the epics #64 and#66. We have decided that this work doesn't need its own ticket.
