### ISSUE TITLE
Write local-client function for accepting a request to store a secret

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#70]
This function should take secret material as input, establish a channel with the server using `tonic`, pass the secret on to the key server for storage, and return either a success or error indicator.

Eventually this function should also check that the session is still authenticated and return the appropriate error if it is not.

**Comment by marsella** [comment]
Re: checking authentication. The vision I have for the session is that authentication errors will pop up when you try to send something over a channel. So I don't expect a separate "check authentication" step before sending -- I think we can just try to send and propagate any error that occurs.

**Comment by marsella** [comment]
Per boltlabs-inc/key-mgmt-spec#14, the local client will not have generate (#69) and store as separate APIs. When a user requests to generate a secret, the system generates it, encrypts it, and stores it both locally and remotely.

**Comment by picklenerd** [comment]
#69 covers both generation and storage of secrets.
