### ISSUE TITLE
Write key-server function to implement "generate and store a secret" flow

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#72]
This function will establish a channel with the client using the pattern established in #117. Once the channel is established, it will implement the "generate and store a secret" flow described [in the spec](https://github.com/boltlabs-inc/key-mgmt-spec/blob/main/cryptographic_flows.md#generate-and-store-a-secret).

**Comment by marsella** [comment]
We might want spin out "store it" into a separate issue / PR to define
- database configuration details
- the minimum API needed for this issue (store/retrieve)
- implementation of that API

**Comment by vidyaap** [comment]
Yep, now that we've had the DB conversation I'm going to go back and flesh out anything that had to do with that (this involved a lot of the key-server issues and the audit log issues)

**Comment by vidyaap** [comment]
Superseded by #136
