### ISSUE TITLE
Remove local-client CLI and binary

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#79]
Right now, the dams-local-client crate exposes a binary as well as a `cli` module as part of the library and the binary.  Those things are currently there to make testing easier, but eventually, the client should not operate with a CLI, and instead only the API module should be exposed in the library. 

This issue is can be closed when:
- [x] The client operations that are currently only accessible through CLI functions have another way of being called.
- [x] The dams-local-client Cargo.toml no longer exposes a binary.
- [x] The dams-local-client library no longer exposes a `cli` module or a `command` module.

**Comment by marsella** [comment]
This can probably be executed in one PR with #80.

**Comment by vidyaap** [comment]
This was also closed by #135
