### ISSUE TITLE
Create demo cli application to show-case our DAMS client library.

### ISSUE THREAD

**Issue by gijsvl** [boltlabs-inc/key-mgmt#80]
To demo appropriate use of the client library at each stage of development, we should make a separate repo with a small application that actually uses the library.

A simple option is to define a command-line interface with commands to trigger each operation. ~It should narrate its progress and can optionally be interactive.~ It should also have a runnable test or example that calls the commands in some informative sequence and narrates its progress.

PRs #55 and #58 defined, then removed, CLIs for registering and authenticating a user. Whoever takes this on can use this as a reference.

This issue is complete when
- [ ] There's a new repo with a simple CLI (or, perhaps, a set of issues to track progress on CLI development)
- [ ] The CLI is completely removed from the local client crate in this repo (including the `Create` and `Retrieve` options created for #3).

**Comment by marsella** [comment]
Re: the second bullet, see details in #79.

**Comment by indomitableSwan** [comment]
Following async discussion, this demo repo should have the following properties: 
- The repo will have the key-mgmt development branch as a dependency.
- The repo can also be used as a playground/scratch space to quickly test things that require more infrastructure to test (as opposed to things you can just test in a single scratch Rust file).
