### ISSUE TITLE
Make first iteration of MongoDB database

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#81]
For this phase, we need to create a database to hold user, secret, and log information.  This database will be accessed by the key server for secret storage and retrieval, as well as audit log storage and retrieval.  This epic includes tasks to:
- pick a MongoDB ORM library for Rust
- create the initial infrastructure for the database (i.e. file structure, plus code to initially setup and connect to the database)
- create models for users, secrets, and logs

**Comment by marsella** [comment]
Does #52 also belong as part of this epic?

**Comment by vidyaap** [comment]
Closed by #95
