### ISSUE TITLE
Change return type in offer_abort! macro

### ISSUE THREAD

**Issue by vidyaap** [boltlabs-inc/key-mgmt#85]
Right now the `offer_abort!` macro returns an `anyhow` error, but that means that API functions in the local client also have to return `anyhow` errors instead of errors that we define.  This issue can be closed when:
- [ ] the `offer_abort!` macro returns a new error type (e.g. `DialecticError`) that we can wrap
- [ ] functions that currently return anyhow errors because of `offer_abort!` return our custom errors instead (e.g. a `SessionError` variant that wraps around the `DialecticError` in the register and authenticate functions)

**Comment by marsella** [comment]
This is now irrelevant with the decision to move away from dialectic. See #98.
