### ISSUE TITLE
Update protocol to reflect authentication requirements

### ISSUE THREAD

**Issue by marsella** [boltlabs-inc/key-mgmt#87]
The key server only accepts connections that conform to a protocol, defined in `protocol.rs`. The high-level dialectic protocol is currently defined as:
```rust
pub type KeyMgmt = Session! {
  choose {
    0 => Create,
    1 => Register,
    2 => Retrieve,
    3 => Authenticate,
  }
};
```
That is, when a client connects to the key server, they can initiate any of the options, and none of them will be rejected.

However, this does not match the actual requirements of our system. In fact a user should start with `Register`, if they haven't already, then `Authenticate`, before they can continue with other operations. 

So, a correct session should look something like (maybe bad syntax):
```rust
pub type KeyMgmt = Session! {
  choose {
    0 => { Register; Authenticate; AuthenticatedOperations; },
    1 => { Authenticate; AuthenticatedOperations },
  }
};

pub type AuthenticatedOperations = Session! {
  loop {
    choose {
      0 => Create,
      1 => Retrieve,
      2 => ...,
    }
  }
};
```
This is closely tied to #30 (generally figuring out session handling) and #34, which essentially requires a way to ensure that any messages sent and received in the course of the `AuthenticatedOperations` have an encryption layer.

To close this issue, 
- [ ] Update the session type to reflect the required order of operations
- [ ] Handle any fallout??

**Comment by indomitableSwan** [comment]
@marsella how does this issue play into the refactor?

**Comment by marsella** [comment]
If we're not using session types, we'll have to do this enforcement some other way. We could probably close it.

**Comment by indomitableSwan** [comment]
> If we're not using session types, we'll have to do this enforcement some other way. We could probably close it.

And where should we capture this requirement instead?
