### ISSUE TITLE
Explore alternative RPC frameworks

### ISSUE THREAD

**Issue by jakinyele** [boltlabs-inc/key-mgmt#99]
### Project Description
To fully assess a switch from Dialectic, this project will explore an alternative client-server architecture using RPC frameworks such as Google’s RPC (or gRPC). The objective is to create a basic client-server using tonic/gRPC and document the required steps for refactoring & integrating into DAMS. tonic is a gRPC over HTTP/2 implementation focused on high performance, interoperability, and flexibility. The tonic library was created to have first-class support of async/await and to act as a core building block for production systems written in Rust. Tonic is well-maintained and appears to have the necessary building blocks to build a scalable client-server architecture for DAMS. 

### Expected Outcome
A client-server using the tonic Rust library that demonstrates a request/response style protocol with simple data types.

**Comment by picklenerd** [comment]
We're moving forward with tonic. @vidyaap made a nice demo (https://github.com/boltlabs-inc/dams-tonic-toy) that covers the basics and this demo is now being used as a reference for refactoring everything to use tonic. Refactoring is being tracked in #98 so I'm closing this epic.

If we need to revisit other RPC frameworks in the future, we can re-open this or start a new epic.
